### PR TITLE
changes to work with SvelteKit v1.0.0-next.278

### PR DESCRIPTION
**Pull request by krivdat**
While following your tutorial on logrocket.com and trying to replicate the app I had to make some adjustments due to breaking changes introduced in sveltejs/kit (https://github.com/sveltejs/kit/pull/3384)

Btw great tutorial, very helpful and exactly what I needed for my app.

### CODE REVIEW

**Comment by shinokada** [comment]
Great!
When you click sign-out, it returns the following error:

```
event.headers has been replaced by event.request.headers. See https://github.com/sveltejs/kit/pull/3384 for details
Error: event.headers has been replaced by event.request.headers. See https://github.com/sveltejs/kit/pull/3384 for details
    at Object.get (file:///Users/shinichiokada/Svelte/sveltekit-auth-app/.svelte-kit/runtime/server/index.js:2539:10)
    at get (/Users/shinichiokada/Svelte/sveltekit-auth-app/src/routes/api/sign-out.js:5:26)
    at render_endpoint (file:///Users/shinichiokada/Svelte/sveltekit-auth-app/.svelte-kit/runtime/server/index.js:150:25)
    at resolve (file:///Users/shinichiokada/Svelte/sveltekit-auth-app/.svelte-kit/runtime/server/index.js:2663:17)
    at async respond (file:///Users/shinichiokada/Svelte/sveltekit-auth-app/.svelte-kit/runtime/server/index.js:2571:20)
    at async file:///Users/shinichiokada/Svelte/sveltekit-auth-app/node_modules/@sveltejs/kit/dist/chunks/index.js:245:24
```

**Comment by shinokada** [comment]
Change sign-ou.js to the following:

```js
export async function get ({ request }) {
  const cookie = await request.headers.cookie;
	const cookies = parse(cookie || '');
...
```

**Comment by shinokada** [comment]
Opps. It's my bad. You already had it. Sorry.

**Comment by JannikWempe** [comment]
Thanks for the PR. I'll check it later.

**Comment by robots4life** [comment]
> Thanks for the PR. I'll check it later.

When you do, you could also have a look at shadow endpoints, meaning instead of using the `load` function you can do something like this.

`/profile/index.js`
```js
export async function get({ locals }) {
	// do your checks here on condition of availability of locals.user
	console.log(locals);

	if (locals.user) {
		return {
			status: 200,
			body: {
				locals
			}
		};
	} else {
		return {
			status: 302,
			headers: { Location: '/' }
		};
	}
}
```
Here is a simple little demo. https://github.com/robots4life/cookie-auth

**Comment by JannikWempe** [comment]
@robots4life thanks for pointing that out. For now, I'll stick with the `load` function as it is closer to the initial article and I (currently) find it more readable.

**Pull request merged**
